# Generated by Django 3.2.7 on 2021-11-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='gender',
            field=models.CharField(choices=[('ML', 'Male'), ('FM', 'Female'), ('OT', 'Other')], default='ML', max_length=2),
        ),
    ]
