# Generated by Django 3.2.7 on 2021-11-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0002_children_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='weight',
            field=models.FloatField(),
        ),
    ]
