# Generated by Django 3.2.7 on 2021-11-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0003_alter_children_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
