# Generated by Django 3.2.7 on 2021-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0005_diaperchangelogs_growthlogs_sleeplogs_vaccinationlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaperchangelogs',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
