# Generated by Django 3.2.7 on 2021-12-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0006_alter_diaperchangelogs_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationlogs',
            name='date',
            field=models.DateField(),
        ),
    ]
