# Generated by Django 3.2.7 on 2021-12-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logs', '0008_alter_sleeplogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='growthlogs',
            name='datetime',
            field=models.DateField(),
        ),
    ]
